# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "master" do |master|
    # master.vm.box = "Fedora-Cloud-Base-Vagrant-22-20150521.x86_64.vagrant-virtualbox.box"
    master.vm.box = "hfm4/centos7"
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.hostname = "salt-master"
    # config.vm.synced_folder "../data", "/vagrant_data"
    master.vm.provider "virtualbox" do |vb|
    #   vb.gui = true
      vb.memory = "1024"
    end
    master.vm.provision :salt do |salt|
      salt.install_master = true
      salt.install_type = "stable"
      salt.master_config = "salt/master"
      salt.master_key = "salt/files/master.pem"
      salt.master_pub = "salt/files/master.pub"
      salt.seed_master = {
        master: "salt/files/master.pub",
        web1: "salt/files/web1.pub",
        web2: "salt/files/web2.pub"}
    end
  end
  ### Web Node 1 CentOS 7
  config.vm.define "web1" do |web1|
    web1.vm.box = "hfm4/centos7"
    web1.vm.hostname = "web1"
    web1.vm.network "private_network", ip: "192.168.33.11"
    web1.vm.network "forwarded_port", guest:80, host:8080
    web1.vm.provider "virtualbox" do |vb|
    #   vb.gui = true
      vb.memory = "256"
    end
    web1.vm.provision :salt do |salt|
      salt.install_master = false
      salt.minion_config = "salt/minion"
      salt.minion_key = "salt/files/web1.pem"
      salt.minion_pub = "salt/files/web1.pub"
    end
  end
  ### Web Node 2 Ubuntu 12.04
  config.vm.define "web2" do |web2|
    web2.vm.box = "hashicorp/precise64"
    web2.vm.hostname = "web2"
    web2.vm.network "private_network", ip: "192.168.33.12"
    web2.vm.network "forwarded_port", guest:80, host:8081
    web2.vm.provider "virtualbox" do |vb|
    #   vb.gui = true
      vb.memory = "256"
    end
    web2.vm.provision :salt do |salt|
      salt.install_master = false
      salt.minion_config = "salt/minion"
      salt.minion_key = "salt/files/web2.pem"
      salt.minion_pub = "salt/files/web2.pub"
    end
  end
end
